name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: Upgrade pip, setuptools, and wheel
    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Step 5: Run Python script or tests
    - name: Run Python script
      run: python my_script.py

